### PR TITLE
Make readme more readable by hiding benchmark results under <details> tag

### PR DESCRIPTION
**Pull request by nazar-pc**

### CODE REVIEW

**Comment by jorangreef** [comment]
Thanks @nazar-pc this is a good suggestion.

I am nearly done with a new major version, and will use that to add a table of contents to the README, rather than the `details` tag. I don't want to introduce HTML markup into a markdown file. I know one can, but would rather solve this with a table of contents.

**Comment by nazar-pc** [comment]
Without `<details>` is is very inconvenient to scroll the page back and forth. Table of contents will only solve the inconvenience partially.

**Comment by jorangreef** [comment]
Sure, but `<details>` will only work when viewed as HTML, not in the Terminal or in Markdown viewers that don't support embedded HTML tags. At the end of the day, it's a Markdown document, not an HTML file, otherwise it would have been written as an HTML document. Furthermore, the performance numbers are important.

**Comment by nazar-pc** [comment]
What about moving benchmark results into their own file?

**Comment by jorangreef** [comment]
That would mean another file in the repo, and indirection, all in the name of reducing scrolling. The numbers need to be visible at first glance, e.g. when doing design estimates. It's a core function of the README, more so than any other section.

**Pull request closed without merging**
